name = "personal-analysis"
pages_build_output_dir = "public"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
AI_MODEL_NAME = "meta-llama/llama-4-scout-17b-16e-instruct"
